# Generated by Django 5.2.17 on 2026-09-22 04:34

import apps.experience.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('short_description_bn', models.CharField(blank=True, max_length=160)),
                ('short_description_en', models.CharField(blank=True, max_length=160)),
                ('description_bn', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('tagline_bn', models.CharField(blank=True, max_length=120)),
                ('tagline_en', models.CharField(blank=True, max_length=120)),
                ('keywords_bn', models.CharField(blank=True, max_length=255)),
                ('keywords_en', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bn', models.TextField()),
                ('text_en', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice')], default='single_choice', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('min_age', models.SmallIntegerField()),
                ('max_age', models.SmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_age__lte', models.F('max_age'))), name='chk_agegroup_min_lte_max')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('companion_trait', models.CharField(blank=True, choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friends'), ('destination_first', 'Destination first')], max_length=20, null=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('timed_out', 'Timed out')], default='started', max_length=20)),
                ('kiosk_identifier', models.CharField(default=apps.experience.models.default_kiosk_identifier, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='experience.agegroup')),
                ('primary_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='experience.persona')),
                ('secondary_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='experience.persona')),
                ('questionnaire_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='experience.questionnaireversion')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonaAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20)),
                ('image', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='experience.agegroup')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='experience.persona')),
            ],
            options={
                'ordering': ['persona__sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bn', models.CharField(max_length=255)),
                ('text_en', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('companion_trait', models.CharField(blank=True, choices=[('solo', 'Solo'), ('couple', 'Couple'), ('family', 'Family'), ('friends', 'Friends'), ('destination_first', 'Destination first')], max_length=20, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='experience.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='experience.questionnaireversion'),
        ),
        migrations.CreateModel(
            name='AssessmentPersonaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.PositiveSmallIntegerField()),
                ('normalized_score', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_scores', to='experience.assessmentsession')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='experience.persona')),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'persona'), name='uniq_score_assessment_persona')],
            },
        ),
        migrations.CreateModel(
            name='AnswerPersonaWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=0)),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='experience.answeroption')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_weights', to='experience.persona')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('answer_option', 'persona'), name='uniq_weight_option_persona'), models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 5)), name='chk_weight_0_to_5')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='experience.answeroption')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='experience.assessmentsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='experience.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assessment', 'question'), name='uniq_answer_assessment_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uniq_option_question_order'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['questionnaire_version', 'is_active', 'order'], name='idx_q_version_active'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('questionnaire_version', 'order'), name='uniq_question_version_order'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['status'], name='idx_asm_status'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['started_at'], name='idx_asm_started'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['completed_at'], name='idx_asm_completed'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['primary_persona'], name='idx_asm_primary'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['kiosk_identifier'], name='idx_asm_kiosk'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['age_group'], name='idx_asm_agegroup'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['gender'], name='idx_asm_gender'),
        ),
    ]
