# Generated by Django 5.2.17 on 2026-09-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentanswer',
            name='answer_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='experience.answeroption'),
        ),
    ]
