# Generated by Django 5.2.17 on 2026-09-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_assessmentanswer_answer_option'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questionnaireversion',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_version_name_version'),
        ),
    ]
