# Generated by Django 5.2.17 on 2026-09-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_questionnaireversion_uniq_version_name_version'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessmentanswer',
            index=models.Index(fields=['answer_option'], name='idx_asmanswer_option'),
        ),
    ]
