# Generated by Django 5.2.17 on 2026-09-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_persona_tie_break_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='visitor_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
