# Generated by Django 5.2.17 on 2026-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_three_age_groups_and_rebuild_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='language',
            field=models.CharField(default='bn', max_length=8),
        ),
    ]
